export const tagTypes = {
  auth: "Auth",
  users: "Users",
  user: "User",
  otp: "Otp",
  shift: "Shift",
  shifts: "Shifts",
  subAdmins: "subAdmins",
  clinics: "clinics",
  notifications: "notifications",
  notification: "notification",
  product: "product",
  payment: "payment",
  package: "package",
  setting: "setting",
  support: "support",
  banner: "banner",
};

export const tagTypesList = [
  tagTypes.otp,
  tagTypes.auth,
  tagTypes.users,
  tagTypes.user,
  tagTypes.shift,
  tagTypes.shifts,
  tagTypes.subAdmins,
  tagTypes.clinics,
  tagTypes.notifications,
  tagTypes.notification,
  tagTypes.product,
  tagTypes.payment,
  tagTypes.package,
  tagTypes.setting,
  tagTypes.support,
];
