export const tagTypes = {
  auth: "Auth",
  users: "Users",
  user: "User",
  otp: "Otp",
  notifications: "notifications",
  notification: "notification",
  product: "product",
  setting: "setting",
  support: "support",
  client: "client",
  clients: "clients",
  closer: "closer",
  closers: "closers",
  leagues: "leagues",
  league: "league",
  meta: "meta",
  badges: "badges",
  badge: "badge",
};

export const tagTypesList = [
  tagTypes.otp,
  tagTypes.auth,
  tagTypes.users,
  tagTypes.user,
  tagTypes.notifications,
  tagTypes.notification,
  tagTypes.setting,
  tagTypes.support,
  tagTypes.client,
  tagTypes.clients,
  tagTypes.closer,
  tagTypes.closers,
  tagTypes.leagues,
  tagTypes.league,
  tagTypes.meta,
];
